name: Build

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Build
        uses: samuelmeuli/action-electron-builder@v1.3.0
        with:
          github_token: ${{ github.token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: "build:github"
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}
        env:
          REACT_APP_GIT_COMMIT_HASH: ${{ github.sha }}
          REACT_APP_AUTH_USERPOOLID: ${{ secrets.auth_userpoolid }}
          REACT_APP_AUTH_USERPOOLWEBCLIENTID: ${{ secrets.auth_userpoolwebclientid }}
          REACT_APP_TASKUNIFIER_CLIENT_ID: ${{ secrets.taskunifier_client_id }}
          REACT_APP_TASKUNIFIER_CLIENT_SECRET: ${{ secrets.taskunifier_client_secret }}
          REACT_APP_TOODLEDO_CLIENT_ID: ${{ secrets.toodledo_client_id }}
          REACT_APP_TOODLEDO_CLIENT_SECRET: ${{ secrets.toodledo_client_secret }}

      - name: Move Files
        shell: bash
        run: ./move_dist.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: taskunifier-app-build
          path: build

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: taskunifier-app-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: taskunifier-app-mac
          path: dist-mac

      - name: Upload Win Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: taskunifier-app-win
          path: dist-win
